# global config

cur_bot: bot0
bots: 
  bot0: 
    username: OkBotBotBotBotBot
    name: bot0
    description: "a bot can provide user with some useful suggestion about your living environment to improve your sleep."
  bot1: 
    username: No2hcibot
    name: bot1
    description: "a bot can provide user with some useful suggestion about your physical state(health, diet, and exercise)"
  bot2:
    username: No3HciBot
    name: bot2
    description: "a bot can provide user with some useful suggestion about your mental state(mood, stress...)"

host: bot0

uvicorn:
  host: 0.0.0.0
  port: 8000
openai:
  chatgpt:
    mode:
      free_talk: 
        starting_msg: 
          role: "system"
          content: "You are a helpful assistant."
      pipline: "placeholder"
      default: 
        starting_msg: 
          role: "system"
          content: "You are a helpful assistant."

script_paths:
  introduction: ./template/introduction3Bot.json
  before_bedtime: ./template/message1Bot.json
